language: python
addons:
  apt:
    packages:
      - "python3-pip"
python:
  - "3.6"
install:
  - make && make install
script:
  - coverage run -m unittest discover -s unit_tests -p "test_*.py"
after_success:
  - codecov -t 2d4c33cb-20bc-49ca-9082-e6d686f1cc32
